FROM python:3.12-slim

WORKDIR /app

RUN pip install --no-cache-dir -U pip setuptools

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app.py .
ENV PYTHONUNBUFFERED=1

CMD ["sh", "-c", "opentelemetry-instrument flask --app app run --host=0.0.0.0 --port=${PORT}"]
